name: tabbedmux
version: "1.25"
summary: Graphical tmux interface
description: |
  TabbedMux allows accessing tmux sessions as
  tabs in a Gtk+ UI. It can access local tmux
  instances or remote ones over SSH

confinement: devmode
base: core18

parts:
  tabbedmux:
    plugin: make
    source-type: tar
    source: https://github.com/apmasell/tabbedmux/archive/0829029bd42fb3ab5d9915684123014c727b3c0d.tar.gz
    build-packages:
      - valac
      - make
      - libssh2-1-dev
      - libvte-2.91-dev
      - libgee-0.8-dev
      - libgtk-3-dev
      - libnotify-dev
      - libglib2.0-dev
      - libglib2.0-bin
      - libxml2-utils
    stage-packages:
      - libgee-0.8-2
      - libglib2.0-0
      - libgtk-3-0
      - libnotify4
      - libpango-1.0-0
      - libssh2-1
      - libvte-2.91-0
      - tmux 

apps:
  tabbedmux:
    command: tabbedmux
